// Shared ethics/conduct content — canonical source for both /get-started and
// /contribute so the two pages don't drift into two different sets of rules.
export interface Guideline {
  icon: string;
  title: string;
  severity: 'critical' | 'high' | 'positive';
  desc: string;
}

export const guidelines: Guideline[] = [
  {
    icon: '🚫',
    title: 'No AI-Generated Code Plagiarism',
    severity: 'critical',
    desc: 'Submitting code generated by ChatGPT, Copilot, or Claude as your own without deep understanding is plagiarism. Open source maintainers easily detect this, and many major projects ban it. Doing so will get you blacklisted.',
  },
  {
    icon: '🚫',
    title: 'No Typos or Spam README Fixes',
    severity: 'critical',
    desc: "Fixing single-letter typos in READMEs, adding random empty lines, or changing indentation just to artificially inflate your PR count is considered spam. This will result in being blocked and blacklisted from paid programs.",
  },
  {
    icon: '🚫',
    title: 'No Drive-By Pull Requests',
    severity: 'high',
    desc: 'Opening a PR and then ignoring review comments or disappearing for weeks is highly disrespectful to the maintainers. Always follow through on feedback, or close the PR yourself if you cannot continue.',
  },
  {
    icon: '🚫',
    title: 'Do Not Copy-Paste Solutions',
    severity: 'high',
    desc: 'Do not copy code from Stack Overflow, blogs, or other repositories that you do not fully understand. If you cannot explain every single line of your pull request, it is not ready for review.',
  },
  {
    icon: '✅',
    title: 'Use AI for Learning, Not as a Shortcut',
    severity: 'positive',
    desc: 'Using AI to explain a complex codebase algorithm, debug a local compiler error, or clarify a programming syntax is perfectly fine. Leverage AI to learn faster, but always write and understand the final code yourself.',
  },
];
